### ISSUE TITLE
[org.freedesktop.DBus.Error.TimedOut] ("Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)",)

### ISSUE THREAD

**Issue by Arachne0** [idreesshaikh/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning#11]
While following the instructions in Read.md, I encountered an error after running cd poetry and poetry update. I am not sure how to resolve the error. I am using CARLA 0.9.8 version on Linux.

**Comment by Arachne0** [comment]
I started approaching it simply by giving up on continuous poetry updates, as I was facing consistent failures. Since the Python Carla library didn't have version 0.9.8 available, I upgraded to version 0.9.14 first. I also realized that the issue could be resolved by adjusting the Torch version since I was using an RTX 3070 GPU. I'm not sure why I'm using poetry as a dependency manager. If possible, I would like to hear the reason behind it.

**Comment by idreesshaikh** [comment]
Hi, I'd ask you to run the code on windows since it was written on windows. I'm unsure what error you're getting. I do not have much experience on linux either to help you resolve the issue unfortunately. 

Moreover, I'd ask you to use a different **dependency manager/env manager** like `anaconda` or `miniconda` to help resolve this issue. You can find the `requirements.txt` file in the root of the repository to know which dependencies you need to install. Thanks
